### ISSUE TITLE
include fetching of feeds

### ISSUE THREAD

**Issue by fdietz** [fdietz/elixir-feed-parser#3]
It should be possible to fetch a feed via URL and process it:

```
feed = ElixirFeedParser.fetch_and_parse(feed_url)
```

Known problems:
- Some feeds do not respond without user-agent

**Comment by andreapavoni** [comment]
Please, don't. This lib is ok as is: it offers feed parsing functionality, no matter if the parsed xml comes from a file or it was downloaded from an URL through another lib. Why adding a dependency that eventually is not needed buy the final user? :-)

my 2 cents
